/var/log/trendatlas-research/*.log {
    daily
    rotate 7
    maxsize 10M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    su trendatlas-research trendatlas-research
}
